# Generated by Django 3.1.1 on 2020-09-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='user_profile',
            new_name='user',
        ),
    ]
