# Generated by Django 3.1.1 on 2020-09-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200901_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
