# Generated by Django 3.1.1 on 2020-09-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
