# Generated by Django 3.1.1 on 2020-09-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('items', '0008_item_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
