# Generated by Django 3.1.1 on 2020-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20200903_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
