# Generated by Django 3.1.1 on 2020-09-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_file_upload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
