# Generated by Django 3.1.1 on 2020-09-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20200903_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='upload_name',
        ),
    ]
