# Generated by Django 3.1.1 on 2020-09-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_comment_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_items', to='items.item')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_items', to='items.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='related_items',
            field=models.ManyToManyField(related_name='_item_related_items_+', through='items.ItemRelation', to='items.Item'),
        ),
    ]
